In [1]:
!unzip COLAB_CMO_A2.zip

Archive:  COLAB_CMO_A2.zip
  inflating: CMO_A2.py               
   creating: pyarmor_runtime_000000/
  inflating: pyarmor_runtime_000000/pyarmor_runtime.so  
  inflating: pyarmor_runtime_000000/__init__.py  


In [2]:
import numpy as np

In [30]:
import decimal

In [3]:
import CMO_A2

###################### Problem-4 ####################
####################################################



In [16]:
E = np.identity(5)

In [22]:
U = np.zeros((5,5))

In [23]:
# initialize conjugate gradient u_0
U[0] = E[0]


In [24]:
# call oracle for Q-matrix

Q = CMO_A2.oracle4(21044)

In [25]:
Q

array([[20., 17., 17., 17., 17.],
       [17., 18., 17., 17., 17.],
       [17., 17., 22., 17., 17.],
       [17., 17., 17., 24., 17.],
       [17., 17., 17., 17., 23.]])

In [87]:
np.linalg.eig(Q)

(array([89.45402241,  1.65768798,  3.78082332,  5.48806947,  6.61939682]),
 array([[ 0.43955389,  0.42696534,  0.7734406 , -0.13655903,  0.0873741 ],
        [ 0.42961531, -0.87141734,  0.21717326, -0.07570479,  0.05627678],
        [ 0.4499632 ,  0.17147433, -0.49535106, -0.6961475 ,  0.19528355],
        [ 0.46087748,  0.10727953, -0.1876009 ,  0.22472484, -0.83089572],
        [ 0.45535495,  0.13198515, -0.27213717,  0.6637001 ,  0.51056374]]))

In [38]:
# loop to calculate sigma.

for i in range(1, 5):
  for j in range(i):
    Num = ( ( np.transpose(E[i]).dot(Q) ).dot(U[j]) )
    Den = ( ( np.transpose(U[j]).dot(Q) ).dot(U[j]) )
    S = ( Num/Den ) * U[j]

  U[i] = E[i] - S


In [45]:
print('u_0:', U[0])
print('u_1:', U[1])
print('u_2:', U[2])
print('u_3:', U[3])
print('u_4:', U[4])

u_0: [1. 0. 0. 0. 0.]
u_1: [-0.85  1.    0.    0.    0.  ]
u_2: [ 0.61056338 -0.71830986  1.          0.          0.        ]
u_3: [-0.45919636  0.54023102 -0.75208632  1.          0.        ]
u_4: [ 0.20392766 -0.2399149   0.33399917 -0.44409686  1.        ]


In [ ]:
########################### part-2 ###############

In [84]:
# quadratic form
Q = CMO_A2.oracle4(21044)
b = [2.0, 1.0, 0.0, 4.0, 4.0]

# starting point
x = [0.0, 0.0, 0.0, 0.0, 0.0]

k = 1

max_iter = 5

while k <= max_iter:

  num = b - Q.dot(x)
  den = Q.dot(U[k-1])


  alpha = np.transpose(U[k-1]).dot(num) / np.transpose(U[k-1]).dot(den)

  x = x + alpha*U[k-1]
  k = k + 1

In [85]:
print(x)

[ 0.11678033 -0.01974156 -0.24702646  0.24952833  0.10033953]


In [88]:
fx = (1/2)*np.transpose(x).dot(Q.dot(x)) - np.transpose(b).dot(x)

In [89]:
fx

-0.8523619068407263

In [91]:
# quadratic form/function
Q = CMO_A2.oracle4(21044)
b = [2.0, 1.0, 0.0, 4.0, 4.0]

# starting point
x = [0.0, 0.0, 0.0, 0.0, 0.0]

# while loop iterator
k = 1
max_iter = 5  # k_max = n = 5 as per eigenvectors of matrix Q

# iteration searching the minima
while k <= max_iter:

    # helper variable to calculate step size alpha
    num = b - Q.dot(x)  # numerator to calculate alpha step size
    den = Q.dot(U[k-1]) # denominator to calculate alpha step size

    # step size for progress
    alpha = np.transpose(U[k-1]).dot(num) / np.transpose(U[k-1]).dot(den)

    # iterative update for x
    x = x + alpha*U[k-1]
    k = k + 1


fx = (1/2)*np.transpose(x).dot(Q.dot(x)) - np.transpose(b).dot(x)

print('x_star:', x)
print('fx_star:', round(fx, 9))


x_star: [ 0.11678033 -0.01974156 -0.24702646  0.24952833  0.10033953]
fx_star: -0.852361907


In [92]:
#define canonical co-ordiante axis
E = np.identity(5)

# MAtrix to store conjugate vectors in the matrix-row
U = np.zeros((5,5))

# initialize conjugate gradient u_0
U[0] = E[0]

# call oracle for Q-matrix

Q = CMO_A2.oracle4(21044)

#################### Part-I ##########################################

# loop to calculate conjugate vectors

for i in range(1, 5):
  for j in range(i):
    Num = ( ( np.transpose(E[i]).dot(Q) ).dot(U[j]) )
    Den = ( ( np.transpose(U[j]).dot(Q) ).dot(U[j]) )
    S = ( Num/Den ) * U[j]

  U[i] = E[i] - S

print('u_0:', U[0])
print('u_1:', U[1])
print('u_2:', U[2])
print('u_3:', U[3])
print('u_4:', U[4])

u_0: [1. 0. 0. 0. 0.]
u_1: [-0.85  1.    0.    0.    0.  ]
u_2: [ 0.61056338 -0.71830986  1.          0.          0.        ]
u_3: [-0.45919636  0.54023102 -0.75208632  1.          0.        ]
u_4: [ 0.20392766 -0.2399149   0.33399917 -0.44409686  1.        ]


In [81]:
###################### Problem-1 ####################
####################################################

In [46]:
# variables
x = -1
y = 1

In [47]:
# tolerance
tol=1e-4

# maximum oteration
max_iter = 100

In [48]:
# finding minima iteratively
for i in range(max_iter):

    r = (y + 2*x)/3
    s = (2*y + x)/3

    f_r = CMO_A2.oracle1(21044, r)
    f_s = CMO_A2.oracle1(21044, s)

    if f_r <= f_s:
        x = x
        y = s
    else:
        x = r
        y = y

    if (y-x) < tol:
        break


In [51]:
print( 'num_iteration:', i )
print( 'alpha_star:', round((x+y)/2, 9) )



num_iteration: 24
alpha_star: 0.058814359


In [52]:
g_alpha_star = CMO_A2.oracle1( 21044, (x+y)/2 )
print('g_alpha_star:', round(g_alpha_star, 9) )

g_alpha_star: 17.81381861


###################### Problem-3 ####################
####################################################

In [55]:
from numpy import linalg as LA


In [56]:
x_0 = [0.0, 0.0, 0.0, 0.0, 0.0]

In [64]:
def gradient_descent(x_0, alpha, tol, max_iter):

    x = x_0

    for i in range(max_iter):

        fx, grad_fx = CMO_A2.oracle3(21044, x)
        x = x - (alpha*grad_fx)

        if LA.norm(grad_fx) < tol:
            break

    #print results
    print('num_iteration:', i)
    print('x_star:', x)
    print('f_x_star:', round(fx, 9))

    return None

In [65]:
gradient_descent(x_0, alpha=0.00004, tol=1e-4, max_iter=1000)

num_iteration: 27
x_star: [0.00687022 0.00687022 0.00687022 0.00687022 0.00687022]
f_x_star: 97.930285075


In [ ]:
##############---- 3.2 ------------------

In [74]:

def acc_grad(x_0, theta=0.142, alpha=0.00004, tol=1e-4, max_iter=1000):

    # variables and its initial value
    x_cur = x_0
    x_prev = x_0

    y = (1+theta)*x_cur


    for i in range(max_iter):

        fy, grad_fy = CMO_A2.oracle3(21044, y)

        x_cur = y - (alpha*grad_fy)

        y = x_cur + ( theta*(x_cur - x_prev) )

        x_prev = x_cur

        if LA.norm(grad_fy) < tol:
            break

    #print results
    print('num_iteration:', i)
    print('x_star:', x_cur)

    fx_cur, grad_fx_cur = CMO_A2.oracle3(21044, x_cur)
    print('f_x_star:', round(fx_cur, 9))

    return None


In [75]:
x_0 = np.array([0.0, 0.0, 0.0, 0.0, 0.0])

acc_grad(x_0, theta=0.142, alpha=0.00004, tol=1e-4, max_iter=1000)

num_iteration: 21
x_star: [0.00687022 0.00687022 0.00687022 0.00687022 0.00687022]
f_x_star: 97.930285075


In [78]:
import numpy as np
from numpy import linalg as LA

import CMO_A2

########################## GRADIENT DESCENT ##################################

# initial point
x_0 = [0.0, 0.0, 0.0, 0.0, 0.0]

# iterative gradient descent

def gradient_descent(x_0, alpha, tol, max_iter):

    x = x_0

    for i in range(max_iter):

        fx, grad_fx = CMO_A2.oracle3(21044, x)
        x = x - (alpha*grad_fx)

        if LA.norm(grad_fx) < tol:
            break

    #print results
    print('num_iteration:', i)
    print('x_star:', x)
    print('f_x_star:', round(fx, 9))

    return None

# call function: it prints num_iteration, x and fx. It returns None.

gradient_descent(x_0, alpha=0.00004, tol=1e-4, max_iter=1000)


########################## ACC. GRADIENT DESCENT #############################

def acc_grad_descent(x_0, theta=0.142, alpha=0.00004, tol=1e-4, max_iter=1000):

    # variables and its initial value
    x_cur = x_0
    x_prev = x_0

    y = (1+theta)*x_cur


    for i in range(max_iter):

        fy, grad_fy = CMO_A2.oracle3(21044, y)

        x_cur = y - (alpha*grad_fy)

        y = x_cur + ( theta*(x_cur - x_prev) )

        x_prev = x_cur

        if LA.norm(grad_fy) < tol:
            break

    #print results
    print('num_iteration:', i)
    print('x_star:', x_cur)

    fx_cur, grad_fx_cur = CMO_A2.oracle3(21044, x_cur)
    print('f_x_star:', round(fx_cur, 9))

    return None

# call function: it prints num_iteration, x and fx. It returns None.

x_0 = np.array([0.0, 0.0, 0.0, 0.0, 0.0])

acc_grad_descent(x_0, theta=0.142, alpha=0.00004, tol=1e-4, max_iter=1000)



num_iteration: 27
x_star: [0.00687022 0.00687022 0.00687022 0.00687022 0.00687022]
f_x_star: 97.930285075
num_iteration: 21
x_star: [0.00687022 0.00687022 0.00687022 0.00687022 0.00687022]
f_x_star: 97.930285075


In [82]:
###################### Problem-1 ####################
####################################################

In [80]:
import numpy as np
import CMO_A2

# variables
x = -1
y = 1

# tolerance
tol=1e-4

# maximum oteration
max_iter = 100

# finding minima iteratively
for i in range(max_iter):

    r = (y+2*x)/3
    s = (2*y+x)/3

    f_r = CMO_A2.oracle1(21044, r)
    f_s = CMO_A2.oracle1(21044, s)

    if f_r <= f_s:
        x = x
        y = s
    else:
        x = r
        y = y

    if (y-x) < tol:
        break


# Output results
print( 'num_iteration:', i )
print( 'alpha_star:', round((x+y)/2, 9) )

g_alpha_star = CMO_A2.oracle1( 21044, (x+y)/2 )
print('g_alpha_star:', round(g_alpha_star, 9) )

num_iteration: 24
alpha_star: 0.058814359
g_alpha_star: 17.81381861


In [ ]:
########################### problem-2 #######################
#############################################################

In [105]:
import numpy as np

import CMO_A2

# function and its derivatives
def f_2(x):
    return  2/( (1+2*x**2)**(3/2) )
def f_1(x):
    return 2*x/( (1+2*x**2)**(1/2) )
def f(x):
    return ( 1 + 2*x**2 )**(1/2)

# parameters for back tracking
beta = 0.9
c = 0.1

# initial step-size alpha
alpha = 1
tol = 0.0001

# backtracking to find suitable step-size alpha
k =1 # counter

# initial point
x = 1
while abs(f_1(x)) > tol:
    d = -( ( f_2(x) )**(-1) )*(f_1(x))
    alpha = 1

    while f(x + alpha*d) > f(x) + c*alpha*f_1(x)*d:
        alpha = beta*alpha

    x = x + alpha*d
    k = k+1

# final outputs
print('x_final:', round(x, 9))
print('x_final:', x)
print('num_iteration(k):', k)

x_final: 8.12e-07
x_final: 8.123322162356325e-07
num_iteration(k): 7


x_final: 8.12e-07
x_final: 8.123322162356325e-07
num_iteration(k): 7
